import { jsPDF } from "jspdf";
import "jspdf-autotable";
import { type ContractTemplateId, type ContractData } from "./templates";
import { formatCurrency } from "@/lib/utils";

type Doc = jsPDF;

const PAGE_WIDTH = 210; // A4 mm
const MARGIN = 20;
const CONTENT_WIDTH = PAGE_WIDTH - 2 * MARGIN;
const FONT_SIZE_BODY = 10;
const FONT_SIZE_TITLE = 16;
const FONT_SIZE_SUBTITLE = 12;
const LINE_HEIGHT = 5;

// ─── Helpers ────────────────────────────────────────────────────────

function addHeader(doc: Doc) {
  doc.setFontSize(8);
  doc.setTextColor(100);
  doc.text("Generated by Real Estate Brokerage CRM", MARGIN, 10);
  doc.text(
    new Date().toLocaleDateString("en-PH", {
      year: "numeric",
      month: "long",
      day: "numeric",
    }),
    PAGE_WIDTH - MARGIN,
    10,
    { align: "right" },
  );
  doc.setDrawColor(200);
  doc.line(MARGIN, 13, PAGE_WIDTH - MARGIN, 13);
  doc.setTextColor(0);
}

function addFooter(doc: Doc) {
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(`Page ${i} of ${pageCount}`, PAGE_WIDTH - MARGIN, 295, {
      align: "right",
    });
    doc.setDrawColor(200);
    doc.line(MARGIN, 290, PAGE_WIDTH - MARGIN, 290);
  }
  doc.setTextColor(0);
}

function addSection(
  doc: Doc,
  title: string,
  content: string[],
  y: number,
): number {
  let cursorY = y;

  // Section title
  doc.setFontSize(FONT_SIZE_SUBTITLE);
  doc.setFont("helvetica", "bold");
  doc.text(title, MARGIN, cursorY);
  cursorY += LINE_HEIGHT + 2;

  // Section content
  doc.setFontSize(FONT_SIZE_BODY);
  doc.setFont("helvetica", "normal");

  for (const line of content) {
    const lines = doc.splitTextToSize(line, CONTENT_WIDTH);
    for (const l of lines) {
      if (cursorY > 275) {
        doc.addPage();
        cursorY = MARGIN + 10;
      }
      doc.text(l, MARGIN, cursorY);
      cursorY += LINE_HEIGHT;
    }
  }

  return cursorY + 3;
}

function addField(
  doc: Doc,
  label: string,
  value: string | number | undefined | null,
  y: number,
): number {
  let cursorY = y;
  if (cursorY > 275) {
    doc.addPage();
    cursorY = MARGIN + 10;
  }
  doc.setFontSize(FONT_SIZE_BODY);
  doc.setFont("helvetica", "bold");
  const displayValue =
    value != null /* eslint-disable-line eqeqeq */ ? String(value) : "________________________";
  doc.text(`${label}: `, MARGIN, cursorY);
  const labelWidth = doc.getTextWidth(`${label}: `);
  doc.setFont("helvetica", "normal");
  doc.text(displayValue, MARGIN + labelWidth, cursorY);
  cursorY += LINE_HEIGHT + 1;
  return cursorY;
}

// ─── Renderers ──────────────────────────────────────────────────────

function renderReservationAgreement(doc: Doc, data: ContractData): void {
  let y = MARGIN + 15;

  // Title
  doc.setFontSize(FONT_SIZE_TITLE);
  doc.setFont("helvetica", "bold");
  doc.text("RESERVATION AGREEMENT", PAGE_WIDTH / 2, y, { align: "center" });
  y += LINE_HEIGHT + 5;

  // Party information
  y = addSection(doc, "PARTIES", [], y);
  y = addField(doc, "SELLER", data.sellerName, y);
  if (data.sellerAddress)
    {y = addField(doc, "Seller Address", data.sellerAddress, y);}
  y = addField(doc, "BUYER", data.buyerName, y);
  if (data.buyerAddress)
    {y = addField(doc, "Buyer Address", data.buyerAddress, y);}
  y = addField(doc, "Broker/Agent", data.brokerName, y);
  if (data.brokerLicense)
    {y = addField(doc, "License No.", data.brokerLicense, y);}
  if (data.brokerAgency) {y = addField(doc, "Agency", data.brokerAgency, y);}
  y += 3;

  // Property
  y = addSection(doc, "PROPERTY", [], y);
  y = addField(doc, "Property", data.propertyTitle, y);
  y = addField(
    doc,
    "Address",
    `${data.propertyAddress}, ${data.propertyCity}${data.propertyProvince ? `, ${data.propertyProvince}` : ""}`,
    y,
  );
  y = addField(doc, "Type", data.propertyType, y);
  if (data.lotArea) {y = addField(doc, "Lot Area", `${data.lotArea} sqm`, y);}
  if (data.floorArea)
    {y = addField(doc, "Floor Area", `${data.floorArea} sqm`, y);}
  if (data.tctNumber) {y = addField(doc, "TCT No.", data.tctNumber, y);}
  y += 3;

  // Financial Terms
  y = addSection(doc, "FINANCIAL TERMS", [], y);
  y = addField(doc, "Purchase Price", formatCurrency(data.purchasePrice), y);
  if (data.reservationFee)
    {y = addField(
      doc,
      "Reservation Fee",
      formatCurrency(data.reservationFee),
      y,
    );}
  y = addField(doc, "Date of Agreement", data.dateOfAgreement, y);
  if (data.targetClosingDate)
    {y = addField(doc, "Target Closing", data.targetClosingDate, y);}
  y += 3;

  // Terms and conditions
  const terms = [
    "1. The BUYER hereby reserves the above-described property through the payment of the reservation fee.",
    "2. The reservation fee is NON-REFUNDABLE but shall be applied as part of the down payment should the BUYER proceed with the purchase.",
    "3. This Agreement shall be governed by and construed in accordance with the laws of the Republic of the Philippines.",
    "4. The SELLER warrants that they have the legal capacity and authority to sell the property.",
    `5. The BROKER, ${data.brokerName}, acts as a duly licensed real estate service practitioner under Republic Act No. 9646 (Real Estate Service Act).`,
    "6. Should the BUYER fail to execute the Contract to Sell within the period agreed upon, this Reservation Agreement shall be deemed cancelled and the reservation fee forfeited.",
    "7. Any amendment to this Agreement shall be in writing and signed by all parties.",
  ];
  y = addSection(doc, "TERMS AND CONDITIONS", terms, y);
  y += 3;

  // RA 9646 Disclosure
  const ra9646 = [
    "DISCLOSURE PURSUANT TO REPUBLIC ACT NO. 9646:",
    "The Real Estate Service Act governs the practice of real estate service in the Philippines.",
    "The broker/agent named herein is duly accredited and holds a valid PRC license.",
    "Any questions or complaints regarding this transaction may be directed to the Professional Regulation Commission (PRC) or the Department of Human Settlements and Urban Development (DHSUD).",
  ];
  y = addSection(doc, "STATUTORY DISCLOSURE", ra9646, y);
  y += 3;

  // Signatures
  addSignatures(doc, data, y);
}

function renderContractToSell(doc: Doc, data: ContractData): void {
  let y = MARGIN + 15;

  doc.setFontSize(FONT_SIZE_TITLE);
  doc.setFont("helvetica", "bold");
  doc.text("CONTRACT TO SELL", PAGE_WIDTH / 2, y, { align: "center" });
  y += LINE_HEIGHT + 5;

  // Parties
  y = addSection(doc, "PARTIES", [], y);
  y = addField(doc, "SELLER", data.sellerName, y);
  if (data.sellerAddress)
    {y = addField(doc, "Seller Address", data.sellerAddress, y);}
  y = addField(doc, "BUYER", data.buyerName, y);
  if (data.buyerAddress)
    {y = addField(doc, "Buyer Address", data.buyerAddress, y);}
  y = addField(doc, "Broker/Agent", data.brokerName, y);
  y += 3;

  // Property
  y = addSection(doc, "PROPERTY", [], y);
  y = addField(doc, "Property", data.propertyTitle, y);
  y = addField(
    doc,
    "Address",
    `${data.propertyAddress}, ${data.propertyCity}${data.propertyProvince ? `, ${data.propertyProvince}` : ""}`,
    y,
  );
  y = addField(doc, "Type", data.propertyType, y);
  if (data.tctNumber) {y = addField(doc, "TCT No.", data.tctNumber, y);}
  if (data.lotArea) {y = addField(doc, "Lot Area", `${data.lotArea} sqm`, y);}
  if (data.floorArea)
    {y = addField(doc, "Floor Area", `${data.floorArea} sqm`, y);}
  y += 3;

  // Financial
  y = addSection(doc, "CONSIDERATION", [], y);
  y = addField(
    doc,
    "Total Purchase Price",
    formatCurrency(data.purchasePrice),
    y,
  );
  if (data.downPayment)
    {y = addField(doc, "Down Payment", formatCurrency(data.downPayment), y);}
  if (data.paymentTerms)
    {y = addField(doc, "Payment Terms", data.paymentTerms, y);}
  if (data.targetClosingDate)
    {y = addField(doc, "Closing Date", data.targetClosingDate, y);}
  y += 3;

  // Maceda Law
  const maceda = [
    "MACEDA LAW (R.A. 6552) PROVISIONS:",
    "The Buyer is entitled to the following protections under the Maceda Law:",
    "1. Right to cancel after two years of installment payments with grace period of 60 days.",
    "2. Right to refund of 50% of total payments made after 2 years, plus 5% annually for each year beyond 2 years.",
    "3. Right to assign rights to another buyer with seller's consent.",
    "Should the Buyer default, the Seller shall serve a notarized notice of cancellation.",
  ];
  y = addSection(doc, "STATUTORY PROVISIONS", maceda, y);
  y += 3;

  addSignatures(doc, data, y);
}

function renderDeedOfAbsoluteSale(doc: Doc, data: ContractData): void {
  let y = MARGIN + 15;

  doc.setFontSize(FONT_SIZE_TITLE);
  doc.setFont("helvetica", "bold");
  doc.text("DEED OF ABSOLUTE SALE", PAGE_WIDTH / 2, y, { align: "center" });
  y += LINE_HEIGHT + 5;

  // Parties
  y = addSection(
    doc,
    "KNOW ALL MEN BY THESE PRESENTS:",
    [`This DEED OF ABSOLUTE SALE made and executed by and between:`],
    y,
  );
  y = addField(doc, "SELLER", data.sellerName, y);
  if (data.sellerAddress)
    {y = addField(doc, "Seller Address", data.sellerAddress, y);}
  y = addField(doc, "BUYER", data.buyerName, y);
  if (data.buyerAddress)
    {y = addField(doc, "Buyer Address", data.buyerAddress, y);}
  y += 3;

  // Recitals
  const recitals = [
    "WITNESSETH: That the SELLER is the absolute owner of the property described below;",
    "That the SELLER desires to sell the property to the BUYER;",
    "That the BUYER desires to purchase the property upon the terms and conditions set forth herein.",
  ];
  y = addSection(doc, "RECITALS", recitals, y);
  y += 3;

  // Property
  y = addSection(doc, "PROPERTY DESCRIPTION", [], y);
  y = addField(doc, "Property", data.propertyTitle, y);
  y = addField(
    doc,
    "Address",
    `${data.propertyAddress}, ${data.propertyCity}${data.propertyProvince ? `, ${data.propertyProvince}` : ""}`,
    y,
  );
  if (data.tctNumber) {y = addField(doc, "TCT No.", data.tctNumber, y);}
  if (data.lotArea) {y = addField(doc, "Lot Area", `${data.lotArea} sqm`, y);}
  if (data.floorArea)
    {y = addField(doc, "Floor Area", `${data.floorArea} sqm`, y);}
  y += 3;

  // Sale
  y = addSection(
    doc,
    "SALE AND TRANSFER",
    [
      `For and in consideration of the sum of ${formatCurrency(data.purchasePrice)} (the "Purchase Price"), the SELLER hereby sells, transfers, and conveys the property to the BUYER.`,
      "The SELLER warrants that the property is free from all liens and encumbrances.",
    ],
    y,
  );
  y += 3;

  // Tax computation
  const cgt = data.purchasePrice * 0.06;
  const dst = data.purchasePrice * 0.015;
  const taxInfo = [
    `Capital Gains Tax (CGT) — 6%: ${formatCurrency(cgt)}`,
    `Documentary Stamp Tax (DST) — 1.5%: ${formatCurrency(dst)}`,
    "The SELLER shall be responsible for the CGT. The BUYER shall be responsible for the DST.",
    "Transfer tax and registration fees shall be for the account of the BUYER.",
  ];
  y = addSection(doc, "TAXES AND FEES", taxInfo, y);
  y += 3;

  // Notarial acknowledgment block
  y = addSection(
    doc,
    "ACKNOWLEDGMENT",
    [
      `SIGNED this ${data.dateOfAgreement} in ${data.propertyCity || "________"}, Philippines.`,
    ],
    y,
  );
  y += 3;

  y = addSignatures(doc, data, y);

  // Notary block
  y += 5;
  if (y > 260) {
    doc.addPage();
    y = MARGIN + 10;
  }
  const notaryBlock = [
    "REPUBLIC OF THE PHILIPPINES )",
    `${data.propertyCity || "CITY OF ________"} ) S.S.`,
    "",
    "BEFORE ME, a Notary Public for and in the above jurisdiction, personally appeared:",
    `${data.sellerName} (Seller) — bearing valid government-issued identification,`,
    `${data.buyerName} (Buyer) — bearing valid government-issued identification,`,
    "known to me and to me known to be the same persons who executed the foregoing instrument.",
    "WITNESS MY HAND AND SEAL on the date and place first above written.",
    "",
    "_________________________________",
    "NOTARY PUBLIC",
    "Doc. No. _____; Page No. _____; Book No. _____; Series of _____.",
  ];
  doc.setFontSize(FONT_SIZE_BODY);
  doc.setFont("helvetica", "normal");
  for (const line of notaryBlock) {
    if (y > 285) {
      doc.addPage();
      y = MARGIN + 10;
    }
    doc.text(line, MARGIN, y);
    y += line ? LINE_HEIGHT : 3;
  }
}

function renderLetterOfIntent(doc: Doc, data: ContractData): void {
  let y = MARGIN + 15;

  doc.setFontSize(FONT_SIZE_TITLE);
  doc.setFont("helvetica", "bold");
  doc.text("LETTER OF INTENT", PAGE_WIDTH / 2, y, { align: "center" });
  y += LINE_HEIGHT + 5;

  const lines = [
    data.dateOfAgreement,
    "",
    `${data.sellerName || "Property Owner"}`,
    `${data.propertyAddress || ""}`,
    `${data.propertyCity || ""}`,
    "",
    `Dear ${data.sellerName || "Property Owner"},`,
    "",
    `This letter expresses our client's interest in purchasing the property described as "${data.propertyTitle}" located at ${data.propertyAddress}, ${data.propertyCity}${data.propertyProvince ? `, ${data.propertyProvince}` : ""}.`,
    "",
    `Proposed Purchase Price: ${formatCurrency(data.purchasePrice)}`,
    data.paymentTerms ? `Proposed Payment Terms: ${data.paymentTerms}` : "",
    "",
    "This Letter of Intent is non-binding and is subject to the execution of a formal Contract to Sell or Deed of Absolute Sale.",
    "",
    "We look forward to your favorable response.",
    "",
    "Very truly yours,",
    "",
    "",
    `${data.buyerName}`,
    `Through: ${data.brokerName}`,
  ];

  doc.setFontSize(FONT_SIZE_BODY);
  doc.setFont("helvetica", "normal");
  for (const line of lines) {
    if (!line) {
      y += 3;
      continue;
    }
    if (y > 280) {
      doc.addPage();
      y = MARGIN + 10;
    }
    doc.text(line, MARGIN, y);
    y += LINE_HEIGHT;
  }
}

function renderBrokerEngagement(doc: Doc, data: ContractData): void {
  let y = MARGIN + 15;

  doc.setFontSize(FONT_SIZE_TITLE);
  doc.setFont("helvetica", "bold");
  doc.text("BROKER ENGAGEMENT LETTER", PAGE_WIDTH / 2, y, { align: "center" });
  y += LINE_HEIGHT + 5;

  const lines = [
    data.dateOfAgreement,
    "",
    `${data.buyerName}`,
    `${data.buyerAddress || ""}`,
    "",
    `Dear ${data.buyerName},`,
    "",
    `We are pleased to confirm our engagement as your exclusive real estate broker/agent for the acquisition of the below-described property.`,
    "",
    `Property: ${data.propertyTitle}`,
    `Location: ${data.propertyAddress}, ${data.propertyCity}${data.propertyProvince ? `, ${data.propertyProvince}` : ""}`,
    "",
    "SCOPE OF SERVICES:",
    "1. Property search and identification",
    "2. Negotiation assistance",
    "3. Documentation and compliance",
    "4. Coordination with lenders and government agencies",
    "5. End-to-end transaction management",
    "",
    data.commissionRate
      ? `Commission: ${data.commissionRate}% of the purchase price or as separately agreed.`
      : "Commission: As mutually agreed upon in a separate agreement.",
    "",
    "This engagement shall be governed by the provisions of Republic Act No. 9646 (Real Estate Service Act).",
    "",
    "Please signify your agreement by signing below.",
    "",
    "Sincerely,",
    "",
    "",
    `${data.brokerName}`,
    data.brokerAgency ? data.brokerAgency : "",
    data.brokerLicense ? `License No.: ${data.brokerLicense}` : "",
  ];

  doc.setFontSize(FONT_SIZE_BODY);
  doc.setFont("helvetica", "normal");
  for (const line of lines) {
    if (!line) {
      y += 3;
      continue;
    }
    if (y > 280) {
      doc.addPage();
      y = MARGIN + 10;
    }
    doc.text(line, MARGIN, y);
    y += LINE_HEIGHT;
  }

  y += 5;
  addSignatures(doc, data, y);
}

// ─── Shared ─────────────────────────────────────────────────────────

function addSignatures(doc: Doc, data: ContractData, y: number): number {
  if (y > 250) {
    doc.addPage();
    y = MARGIN + 10;
  }

  doc.setFontSize(FONT_SIZE_BODY);
  doc.setFont("helvetica", "bold");
  doc.text("SIGNATURES", MARGIN, y);
  y += LINE_HEIGHT + 4;
  doc.setFont("helvetica", "normal");

  // Seller
  doc.text("_________________________________", MARGIN, y);
  y += LINE_HEIGHT;
  doc.text(data.sellerSignatory || data.sellerName, MARGIN, y);
  doc.setFontSize(9);
  doc.setTextColor(100);
  doc.text("(SELLER)", MARGIN + 80, y);
  doc.setTextColor(0);
  y += LINE_HEIGHT + 5;

  // Buyer
  doc.setFontSize(FONT_SIZE_BODY);
  doc.text("_________________________________", MARGIN, y);
  y += LINE_HEIGHT;
  doc.text(data.buyerSignatory || data.buyerName, MARGIN, y);
  doc.setFontSize(9);
  doc.setTextColor(100);
  doc.text("(BUYER)", MARGIN + 80, y);
  doc.setTextColor(0);
  y += LINE_HEIGHT + 5;

  // Witness 1
  doc.setFontSize(FONT_SIZE_BODY);
  doc.text("_________________________________", MARGIN, y);
  y += LINE_HEIGHT;
  doc.text(data.witness1 || "________________________", MARGIN, y);
  doc.setFontSize(9);
  doc.setTextColor(100);
  doc.text("(WITNESS)", MARGIN + 80, y);
  doc.setTextColor(0);
  y += LINE_HEIGHT + 5;

  // Witness 2
  doc.setFontSize(FONT_SIZE_BODY);
  doc.text("_________________________________", MARGIN, y);
  y += LINE_HEIGHT;
  doc.text(data.witness2 || "________________________", MARGIN, y);
  doc.setFontSize(9);
  doc.setTextColor(100);
  doc.text("(WITNESS)", MARGIN + 80, y);
  doc.setTextColor(0);
  y += LINE_HEIGHT + 5;

  return y;
}

// ─── Main Entry Point ──────────────────────────────────────────────

export function generateContract(
  templateId: ContractTemplateId,
  data: ContractData,
): jsPDF {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  addHeader(doc);

  switch (templateId) {
    case "reservation-agreement":
      renderReservationAgreement(doc, data);
      break;
    case "contract-to-sell":
      renderContractToSell(doc, data);
      break;
    case "deed-of-absolute-sale":
      renderDeedOfAbsoluteSale(doc, data);
      break;
    case "letter-of-intent":
      renderLetterOfIntent(doc, data);
      break;
    case "broker-engagement":
      renderBrokerEngagement(doc, data);
      break;
  }

  addFooter(doc);

  return doc;
}
